Repository eclipse/jkube, pull requests merged in 2020-11, with the labels that each got.

#467 chore: Upgrade assertj-core to 3.18.0
  CHANGELOG.md
  jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegateTest.java
  jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherAddMissingPartsTest.java
  jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java
  jkube-kit/parent/pom.xml
Labels: dependencies

#460 Added a Quickstart for Implementing your own Custom Enricher
  CHANGELOG.md
  quickstarts/kit/custom-istio-enricher/README.md
  quickstarts/kit/custom-istio-enricher/app/pom.xml
  quickstarts/kit/custom-istio-enricher/app/src/main/java/org/eclipse/jkube/quickstarts/kit/enricher/app/Application.java
  quickstarts/kit/custom-istio-enricher/app/src/main/java/org/eclipse/jkube/quickstarts/kit/enricher/app/HelloController.java
  quickstarts/kit/custom-istio-enricher/istio-enricher/pom.xml
  quickstarts/kit/custom-istio-enricher/istio-enricher/src/main/java/org/eclipse/jkube/quickstart/kit/enricher/istio/IstioEnricher.java
  quickstarts/kit/custom-istio-enricher/istio-enricher/src/main/resources/META-INF/jkube/enricher
  quickstarts/kit/custom-istio-enricher/pom.xml
Labels: documentation

#480 fix: wildfly-jar doesn't depend on common-maven module
  CHANGELOG.md
  jkube-kit/jkube-kit-wildfly-jar/pom.xml
Labels: bug

#483 make build reproducible
  pom.xml
Labels: dependencies

#489 feat: Generator and HealthCheck enrichers for Micronaut framework (JVM)
  CHANGELOG.md
  jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
  jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java
  jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
  jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
  jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/YamlUtil.java
  jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/MapUtilTest.java
  jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/PropertiesUtilTest.java
  jkube-kit/common/src/test/resources/util/test-application.properties
  jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricher.java
  jkube-kit/jkube-kit-micronaut/pom.xml
  jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/MicronautUtils.java
  jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricher.java
  jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java
  jkube-kit/jkube-kit-micronaut/src/main/resources/META-INF/jkube/enricher-default
  jkube-kit/jkube-kit-micronaut/src/main/resources/META-INF/jkube/generator-default
  jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsGetMicronautConfigurationTest.java
  jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsTest.java
  jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricherTest.java
  jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/generator/MicronautGeneratorTest.java
  jkube-kit/jkube-kit-micronaut/src/test/resources/utils-test/port-config/json/application.json
  jkube-kit/jkube-kit-micronaut/src/test/resources/utils-test/port-config/properties/application.properties
  jkube-kit/jkube-kit-micronaut/src/test/resources/utils-test/port-config/yaml/application.yml
  jkube-kit/pom.xml
  kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
  kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_generator.adoc
  kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_micronaut.adoc
  kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_micronaut.adoc
  kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_quarkus.adoc
  kubernetes-maven-plugin/plugin/pom.xml
  kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
  openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
  quickstarts/maven/micronaut/README.md
  quickstarts/maven/micronaut/pom.xml
  quickstarts/maven/micronaut/src/main/java/org/eclipse/jkube/quickstart/micronaut/custom/Application.java
  quickstarts/maven/micronaut/src/main/java/org/eclipse/jkube/quickstart/micronaut/custom/Resource.java
  quickstarts/maven/micronaut/src/main/resources/application.yml
  quickstarts/maven/micronaut/src/main/resources/logback.xml
Labels: enhancement
